# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - pinpointscoreclubhouse

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://pinpointscore.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f71f71c1491e41a19bede93457ee00c1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c3fd52a41aa14e1e966a28bb6900a6b1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: pinpointscore.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f71f71c1491e41a19bede93457ee00c1 }}/pinpointscore/clubhouse:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pinpointscoreclubhouse'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e0bfe20eb0ea4ad4b0fe4be3dc6afce6 }}
        images: 'pinpointscore.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f71f71c1491e41a19bede93457ee00c1 }}/pinpointscore/clubhouse:${{ github.sha }}'