# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: pinpointscorecourse

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://pinpointscore.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_665704a1cd834ca78c9d065ca7c3d7b0 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_c20c5c06d0744cfcbb68fec7d75d38d9 }}

      - name: Build and push container image to registry

        uses: docker/build-push-action@v3
        with:
          push: true
          tags: pinpointscore.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_665704a1cd834ca78c9d065ca7c3d7b0 }}/pinpointscore/course:${{ github.sha }}
          file: ./course/Dockerfile
          context: ./course
          build-args: |
            PUBLIC_KEY=${{ secrets.VITE_PUBLIC_KEY }}
            PRIVATE_KEY=${{ secrets.VITE_PRIVATE_KEY }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "pinpointscorecourse"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_34b8cf546ffd41e8a160f3a52eeb6019 }}
          images: "pinpointscore.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_665704a1cd834ca78c9d065ca7c3d7b0 }}/pinpointscore/course:${{ github.sha }}"
